apiVersion: apps/v1
kind: Deployment
metadata:
  name: studybuddy_app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studybuddy_app
  template:
    metadata:
      labels:
        app: studybuddy_app
    spec:
    containers:
    - name: studybuddy_app
      image: dataguru97/studybuddy:v17
      ports:
      - containerPort: 8501
      env:
      - name: GROQ_API_KEY
      valueFrom:
        secretKeyRef:
          name: groq-api-secret
          key: GROQ_API_KEY